name: harvest and transform

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install go-task 3.2.2
      run: |
        wget --no-verbose -O task.tar.gz https://github.com/go-task/task/releases/download/v3.2.2/task_linux_amd64.tar.gz
        sudo tar -xzf task.tar.gz -C /usr/local/bin task && rm task.tar.gz
    - name: install metha 0.2.20
      run: |
        wget --no-verbose -O metha.deb https://github.com/miku/metha/releases/download/v0.2.20/metha_0.2.20_amd64.deb
        sudo apt-get install -y ./metha.deb && rm metha.deb
    - name: install xml_split
      run: sudo apt-get install -y xml-twig-tools
    - name: install xmllint
      run: sudo apt-get install -y libxml2-utils
    - name: install OpenRefine and openrefine-client
      run: task install
    - name: task default
      run: task default
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: OpenRefine project(s)
        path: .openrefine/data/*.openrefine.tar.gz
        retention-days: 1
    - name: git commit and push
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        task git
